version: "3.8"

services:
  back-end:
    build:
      context: .
    image: pedrojunqueira/natours-fastapi
    ports:
      - 8085:80
    env_file:
      - ./natours/.env
    volumes:
      - ./logs/:/backend/logs
  frontend:
    build:
      context: ./natours-frontend
    image: pedrojunqueira/natours-vue
    ports:
      - 80:80
    env_file:
      - ./natours-frontend/.env
    depends_on:
      - back-end
